-- URLs a merchant registers to receive events. Each endpoint has its OWN
-- signing secret, separate from the merchant's API key — so a leaked webhook
-- secret can't be used to call the API, and it can be rotated independently.
CREATE TABLE webhook_endpoints (
    id              UUID PRIMARY KEY,
    merchant_id     UUID NOT NULL REFERENCES merchants(id) ON DELETE CASCADE,

    url             TEXT NOT NULL,

    -- The secret used to compute X-Sandbox-Signature for deliveries to this
    -- endpoint. Generated by the crypto crate, shown to the merchant once.
    signing_secret  TEXT NOT NULL,

    -- Which event types this endpoint wants. Empty array = all events.
    enabled_events  TEXT[] NOT NULL DEFAULT '{}',

    -- Auto-disabled after prolonged total failure; also manually toggleable.
    disabled_at     TIMESTAMPTZ,

    created_at      TIMESTAMPTZ NOT NULL,

    CONSTRAINT webhook_url_shape CHECK (url ~* '^https?://')
);

CREATE INDEX webhook_endpoints_merchant_idx ON webhook_endpoints (merchant_id);